/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeOptimizerSimple: typeof import('./src/components/CodeOptimizerSimple.vue')['default']
    CodeSuggestionPanel: typeof import('./src/components/CodeSuggestionPanel.vue')['default']
    ComplexityGauge: typeof import('./src/components/charts/ComplexityGauge.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MathJax: typeof import('./src/components/MathJax.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PerformanceChart: typeof import('./src/components/charts/PerformanceChart.vue')['default']
    PerformanceControlPanel: typeof import('./src/components/PerformanceControlPanel.vue')['default']
    PerformanceMonitor: typeof import('./src/components/PerformanceMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleEditor: typeof import('./src/components/RuleEditor.vue')['default']
    RulesManager: typeof import('./src/components/RulesManager.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    ThreeJSFieldVisualization: typeof import('./src/components/ThreeJSFieldVisualization.vue')['default']
  }
}
